/**
 * YouTube transcript fetcher via the Apify actor `starvibe/youtube-video-transcript`
 * (locked in per plan §6.5). This is the primary path for both cloud and local
 * ingestion runs — Apify proxies bypass the data-center IP blocks that the
 * Python `youtube-transcript-api` lib hits.
 *
 * Actor input shape (verified against Apify docs):
 *   { startUrls: ["https://www.youtube.com/watch?v=<id>", ...] }
 *
 * Actor output shape (per item in the dataset):
 *   {
 *     videoId, videoUrl, title, channelName,
 *     transcript: [{ text, start, duration }],   // segments
 *     transcriptText: "joined plain text",
 *     language, isAutoGenerated, ...
 *   }
 *
 * The actor's exact output field names can drift across versions; we treat the
 * normalizer in `parseActorItem` as the single source of truth and degrade
 * gracefully when fields are missing.
 */

import { ApifyClient } from "apify-client";
import { requireEnv } from "../shared/env.js";
import { createLogger } from "../shared/logger.js";

const log = createLogger("ingest:youtube-transcript");

const ACTOR_ID = "starvibe/youtube-video-transcript";
const RUN_TIMEOUT_SECONDS = 240;

export interface TranscriptSegment {
  text: string;
  start: number;
  duration: number;
}

export interface TranscriptResult {
  videoId: string;
  text: string;
  segments: TranscriptSegment[];
  language?: string;
  languageName?: string;
  isAutoGenerated?: boolean;
  status: "ok" | "unavailable" | "partial";
}

export interface TranscriptFailure {
  videoId: string;
  error: string;
  status: "unavailable";
}

let client: ApifyClient | null = null;
function getClient(): ApifyClient {
  if (!client) {
    const token = requireEnv("APIFY_API_TOKEN", "Apify API token from console.apify.com → Integrations → API tokens");
    client = new ApifyClient({ token });
  }
  return client;
}

function parseActorItem(item: Record<string, unknown>, expectedVideoId: string): TranscriptResult | TranscriptFailure {
  // The actor sometimes embeds an error on the item rather than failing the run.
  const errorField = item["error"] ?? item["errorMessage"];
  if (typeof errorField === "string" && errorField.length > 0) {
    return { videoId: expectedVideoId, error: errorField, status: "unavailable" };
  }

  // Try multiple plausible field names for the segments + text.
  const segmentsRaw =
    (item["transcript"] as unknown[] | undefined) ??
    (item["transcripts"] as unknown[] | undefined) ??
    (item["captions"] as unknown[] | undefined) ??
    [];

  const segments: TranscriptSegment[] = [];
  for (const seg of segmentsRaw) {
    if (!seg || typeof seg !== "object") continue;
    const s = seg as Record<string, unknown>;
    const text = String(s["text"] ?? s["caption"] ?? "").trim();
    const start = Number(s["start"] ?? s["startSeconds"] ?? s["offset"] ?? 0);
    const duration = Number(s["duration"] ?? s["dur"] ?? 0);
    if (text) segments.push({ text, start, duration });
  }

  let text = String(item["transcriptText"] ?? item["text"] ?? item["fullText"] ?? "").trim();
  if (!text && segments.length > 0) {
    text = segments.map((s) => s.text).join(" ");
  }

  if (!text || segments.length === 0) {
    return { videoId: expectedVideoId, error: "empty transcript returned by actor", status: "unavailable" };
  }

  const language = (item["language"] as string | undefined) ?? (item["languageCode"] as string | undefined);
  const languageName = item["languageName"] as string | undefined;
  const isAutoGenerated = (item["isAutoGenerated"] as boolean | undefined) ?? (item["isGenerated"] as boolean | undefined);

  return {
    videoId: expectedVideoId,
    text,
    segments,
    ...(language && { language }),
    ...(languageName && { languageName }),
    ...(isAutoGenerated !== undefined && { isAutoGenerated }),
    status: "ok",
  };
}

/**
 * Fetch a single transcript via the starvibe Apify actor. Returns a `status`
 * field rather than throwing on an unavailable transcript so callers can write
 * a stub Markdown file instead of failing the whole run.
 */
export async function fetchTranscript(videoId: string): Promise<TranscriptResult | TranscriptFailure> {
  const url = `https://www.youtube.com/watch?v=${videoId}`;
  const t0 = Date.now();
  try {
    const run = await getClient().actor(ACTOR_ID).call(
      { startUrls: [url] },
      { timeout: RUN_TIMEOUT_SECONDS, waitSecs: RUN_TIMEOUT_SECONDS },
    );
    if (run.status !== "SUCCEEDED") {
      return { videoId, error: `Actor status ${run.status}`, status: "unavailable" };
    }
    const { items } = await getClient().dataset(run.defaultDatasetId).listItems({ limit: 1 });
    const first = items[0] as Record<string, unknown> | undefined;
    if (!first) {
      return { videoId, error: "actor produced no dataset items", status: "unavailable" };
    }
    const parsed = parseActorItem(first, videoId);
    log.info(
      {
        videoId,
        status: parsed.status,
        ms: Date.now() - t0,
        ...(parsed.status === "ok" && {
          segments: parsed.segments.length,
          language: parsed.language,
        }),
          ...(parsed.status === "unavailable" && "error" in parsed && { error: parsed.error }),
      },
      "transcript fetched"
    );
    return parsed;
  } catch (err) {
    const error = err instanceof Error ? err.message : String(err);
    log.error({ videoId, error, ms: Date.now() - t0 }, "transcript fetch threw");
    return { videoId, error, status: "unavailable" };
  }
}

/**
 * Batched version: pass multiple video IDs, returns array in input order.
 * Sends them to the actor as a single startUrls call which is much cheaper
 * than N individual actor runs.
 */
export async function fetchTranscriptsBatch(videoIds: string[]): Promise<Array<TranscriptResult | TranscriptFailure>> {
  if (videoIds.length === 0) return [];
  if (videoIds.length === 1) {
    const only = videoIds[0]!;
    return [await fetchTranscript(only)];
  }
  const startUrls = videoIds.map((id) => `https://www.youtube.com/watch?v=${id}`);
  const t0 = Date.now();
  try {
    const run = await getClient().actor(ACTOR_ID).call(
      { startUrls },
      { timeout: Math.max(RUN_TIMEOUT_SECONDS, videoIds.length * 30), waitSecs: Math.max(RUN_TIMEOUT_SECONDS, videoIds.length * 30) },
    );
    if (run.status !== "SUCCEEDED") {
      log.warn({ videoIds, status: run.status }, "batch run did not succeed; marking all unavailable");
      return videoIds.map((vid) => ({ videoId: vid, error: `Actor status ${run.status}`, status: "unavailable" as const }));
    }
    const { items } = await getClient().dataset(run.defaultDatasetId).listItems({ limit: 1000 });
    // Map by videoId — the actor includes the source URL/videoId in each item.
    const byId = new Map<string, Record<string, unknown>>();
    for (const item of items) {
      const r = item as Record<string, unknown>;
      const vid =
        (r["videoId"] as string | undefined) ??
        (r["id"] as string | undefined) ??
        extractVideoId((r["videoUrl"] ?? r["url"]) as string | undefined);
      if (vid) byId.set(vid, r);
    }
    log.info(
      { batchSize: videoIds.length, datasetItems: items.length, mapped: byId.size, ms: Date.now() - t0 },
      "batch transcript run complete"
    );
    return videoIds.map((vid) => {
      const item = byId.get(vid);
      if (!item) {
        return { videoId: vid, error: "actor returned no item for this id", status: "unavailable" as const };
      }
      return parseActorItem(item, vid);
    });
  } catch (err) {
    const error = err instanceof Error ? err.message : String(err);
    log.error({ videoIds, error }, "batch transcript fetch threw");
    return videoIds.map((vid) => ({ videoId: vid, error, status: "unavailable" as const }));
  }
}

function extractVideoId(url: string | undefined): string | undefined {
  if (!url) return undefined;
  const m = url.match(/[?&]v=([A-Za-z0-9_-]{11})/);
  return m?.[1];
}
