/**
 * YouTube transcript fetcher via the Apify actor `starvibe/youtube-video-transcript`
 * (locked in per plan §6.5). This is the primary path for both cloud and local
 * ingestion runs — Apify proxies bypass the data-center IP blocks that the
 * Python `youtube-transcript-api` lib hits.
 *
 * Actor input schema (verified live via /v2/acts/.../builds/default):
 *   {
 *     youtube_url?: "https://www.youtube.com/watch?v=<id>",   // single-video mode
 *     channel_url?: "https://www.youtube.com/channel/UC...",  // channel mode
 *     max_videos?: number,           // channel mode only, 1-200, default 10
 *     start_date?: "YYYY-MM-DD",     // channel mode only
 *     end_date?:   "YYYY-MM-DD",     // channel mode only
 *     language?:   "en"|"fr"|...,    // ISO 639-1
 *     include_transcript_text?: boolean,  // get joined text in addition to segments
 *   }
 *
 * SherlockV2 uses single-video mode: discovery is via the channel's RSS feed
 * (free, fast, no API key) which gives us videoIds; then we call this actor
 * per video with youtube_url. Avoids paying for re-discovery on every cron
 * tick and keeps idempotency tight.
 */

import { ApifyClient } from "apify-client";
import { requireEnv } from "../shared/env.js";
import { createLogger } from "../shared/logger.js";

const log = createLogger("ingest:youtube-transcript");

const ACTOR_ID = "starvibe/youtube-video-transcript";
const RUN_TIMEOUT_SECONDS = 240;

export interface TranscriptSegment {
  text: string;
  start: number;
  duration: number;
}

export interface TranscriptResult {
  videoId: string;
  text: string;
  segments: TranscriptSegment[];
  language?: string;
  languageName?: string;
  isAutoGenerated?: boolean;
  status: "ok" | "unavailable" | "partial";
}

export interface TranscriptFailure {
  videoId: string;
  error: string;
  status: "unavailable";
}

let client: ApifyClient | null = null;
function getClient(): ApifyClient {
  if (!client) {
    const token = requireEnv("APIFY_API_TOKEN", "Apify API token from console.apify.com → Integrations → API tokens");
    client = new ApifyClient({ token });
  }
  return client;
}

function parseActorItem(item: Record<string, unknown>, expectedVideoId: string): TranscriptResult | TranscriptFailure {
  // The actor sometimes embeds an error on the item rather than failing the run.
  const errorField = item["error"] ?? item["errorMessage"];
  if (typeof errorField === "string" && errorField.length > 0) {
    return { videoId: expectedVideoId, error: errorField, status: "unavailable" };
  }

  // Try multiple plausible field names for the segments. The actor's known
  // schema uses `transcript` for the segments array; `transcripts` and
  // `captions` are defensive fallbacks for version drift.
  const segmentsRaw =
    (item["transcript"] as unknown[] | undefined) ??
    (item["transcripts"] as unknown[] | undefined) ??
    (item["captions"] as unknown[] | undefined) ??
    [];

  const segments: TranscriptSegment[] = [];
  for (const seg of segmentsRaw) {
    if (!seg || typeof seg !== "object") continue;
    const s = seg as Record<string, unknown>;
    const text = String(s["text"] ?? s["caption"] ?? "").trim();
    const start = Number(s["start"] ?? s["startSeconds"] ?? s["offset"] ?? 0);
    const duration = Number(s["duration"] ?? s["dur"] ?? 0);
    if (text) segments.push({ text, start, duration });
  }

  // The actor returns `transcript_text` when include_transcript_text=true.
  // Fall back to legacy/alt field names + reconstruct from segments if needed.
  let text = String(
    item["transcript_text"] ??
    item["transcriptText"] ??
    item["text"] ??
    item["fullText"] ??
    ""
  ).trim();
  if (!text && segments.length > 0) {
    text = segments.map((s) => s.text).join(" ");
  }

  if (!text && segments.length === 0) {
    return { videoId: expectedVideoId, error: "empty transcript returned by actor", status: "unavailable" };
  }

  const language = (item["language"] as string | undefined) ?? (item["languageCode"] as string | undefined);
  const languageName = item["languageName"] as string | undefined;
  const isAutoGenerated = (item["isAutoGenerated"] as boolean | undefined) ?? (item["isGenerated"] as boolean | undefined);

  return {
    videoId: expectedVideoId,
    text: text || segments.map((s) => s.text).join(" "),
    segments,
    ...(language && { language }),
    ...(languageName && { languageName }),
    ...(isAutoGenerated !== undefined && { isAutoGenerated }),
    status: "ok",
  };
}

/**
 * Fetch a single video's transcript via the starvibe actor's youtube_url mode.
 * Returns a discriminated result (TranscriptResult | TranscriptFailure) rather
 * than throwing — callers write a stub Markdown file on failure instead of
 * crashing the whole channel run.
 */
export async function fetchTranscript(videoId: string): Promise<TranscriptResult | TranscriptFailure> {
  const youtube_url = `https://www.youtube.com/watch?v=${videoId}`;
  const t0 = Date.now();
  try {
    const run = await getClient().actor(ACTOR_ID).call(
      {
        youtube_url,
        language: "en",
        include_transcript_text: true,
      },
      { timeout: RUN_TIMEOUT_SECONDS, waitSecs: RUN_TIMEOUT_SECONDS },
    );
    if (run.status !== "SUCCEEDED") {
      return { videoId, error: `Actor status ${run.status}`, status: "unavailable" };
    }
    const { items } = await getClient().dataset(run.defaultDatasetId).listItems({ limit: 1 });
    const first = items[0] as Record<string, unknown> | undefined;
    if (!first) {
      return { videoId, error: "actor produced no dataset items", status: "unavailable" };
    }
    const parsed = parseActorItem(first, videoId);
    log.info(
      {
        videoId,
        status: parsed.status,
        ms: Date.now() - t0,
        ...(parsed.status === "ok" && {
          segments: parsed.segments.length,
          textChars: parsed.text.length,
          language: parsed.language,
        }),
        ...(parsed.status === "unavailable" && "error" in parsed && { error: parsed.error }),
      },
      "transcript fetched"
    );
    return parsed;
  } catch (err) {
    const error = err instanceof Error ? err.message : String(err);
    log.error({ videoId, error, ms: Date.now() - t0 }, "transcript fetch threw");
    return { videoId, error, status: "unavailable" };
  }
}

/**
 * "Batch" wrapper for backward compatibility — actor doesn't support multi-video
 * input, so we just loop. Apify lets us run up to 25 actors concurrently on
 * the FREE plan, so we fan out N at a time to keep wall time reasonable.
 */
export async function fetchTranscriptsBatch(videoIds: string[]): Promise<Array<TranscriptResult | TranscriptFailure>> {
  if (videoIds.length === 0) return [];

  const CONCURRENCY = 5; // gentle on Apify; well under the 25 concurrent-runs limit
  const results: Array<TranscriptResult | TranscriptFailure> = new Array(videoIds.length);

  let cursor = 0;
  async function worker(): Promise<void> {
    while (cursor < videoIds.length) {
      const i = cursor++;
      results[i] = await fetchTranscript(videoIds[i]!);
    }
  }
  await Promise.all(Array.from({ length: Math.min(CONCURRENCY, videoIds.length) }, worker));
  return results;
}
