/**
 * YouTube ingestion pipeline:
 *   1. List recent uploads for a channel via the channel's RSS feed
 *      (no API quota cost, returns up to ~15 most recent videos).
 *   2. Filter to videos not yet seen (per `<source>-state.json`).
 *   3. Fetch transcripts in batch via Apify (`starvibe/youtube-video-transcript`).
 *   4. Render each as Markdown with frontmatter (`ingest/markdown.ts`).
 *   5. Write to `sherlock-context/_raw/youtube/<channel-slug>/<date>-<slug>.md`.
 *   6. Update `_state/youtube-state.json` with the latest seen videoId per channel.
 *
 * The pipeline is idempotent: re-running on the same state produces zero new files.
 */

import { mkdirSync, writeFileSync, existsSync, readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { createLogger } from "../shared/logger.js";
import { stateFilePath, rawDir } from "../shared/paths.js";
import { renderMarkdown, slugify, isoDate } from "./markdown.js";
import { fetchTranscriptsBatch } from "./youtube-transcript.js";

const log = createLogger("ingest:youtube");

export interface VideoMeta {
  videoId: string;
  title: string;
  publishedAt: string;
  url: string;
  channelId: string;
  channelName: string;
}

export interface YouTubeChannelState {
  lastVideoId?: string;
  lastChecked?: string;
  lastError?: string | null;
  knownVideoIds?: string[]; // ring buffer for tighter dedup
}

export interface YouTubeStateFile {
  [channelId: string]: YouTubeChannelState;
}

export interface IngestSummary {
  channelId: string;
  channelName: string;
  discovered: number;
  alreadyKnown: number;
  newWithTranscript: number;
  newWithoutTranscript: number;
  errors: string[];
  durationMs: number;
}

// ─── 1. Discover via RSS ──────────────────────────────────────────────

/** Plain-regex Atom parser; matches the production-tested approach in SherlockKulkarni. */
function parseRSS(xml: string, channelId: string, channelName: string): VideoMeta[] {
  const out: VideoMeta[] = [];
  const entryRegex = /<entry>([\s\S]*?)<\/entry>/g;
  for (const match of xml.matchAll(entryRegex)) {
    const entry = match[1] ?? "";
    const videoId = extractTag(entry, "yt:videoId");
    const title = decodeXml(extractTag(entry, "title") ?? "");
    const published = extractTag(entry, "published") ?? new Date().toISOString();
    if (videoId && title) {
      out.push({
        videoId,
        title,
        publishedAt: published,
        url: `https://www.youtube.com/watch?v=${videoId}`,
        channelId,
        channelName,
      });
    }
  }
  return out;
}

function extractTag(xml: string, tag: string): string | null {
  const re = new RegExp(`<${tag}[^>]*>(.*?)</${tag}>`, "s");
  return re.exec(xml)?.[1]?.trim() ?? null;
}

function decodeXml(s: string): string {
  return s
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'");
}

export async function discoverRecentVideos(
  channelId: string,
  channelName: string
): Promise<VideoMeta[]> {
  const url = `https://www.youtube.com/feeds/videos.xml?channel_id=${channelId}`;
  const res = await fetch(url, { signal: AbortSignal.timeout(15_000) });
  if (!res.ok) {
    throw new Error(`RSS fetch failed for ${channelId}: HTTP ${res.status}`);
  }
  return parseRSS(await res.text(), channelId, channelName);
}

// ─── 2 + 6. State file helpers ────────────────────────────────────────

function loadState(): YouTubeStateFile {
  const path = stateFilePath("youtube");
  if (!existsSync(path)) return {};
  try {
    return JSON.parse(readFileSync(path, "utf-8")) as YouTubeStateFile;
  } catch (err) {
    log.warn({ err: err instanceof Error ? err.message : String(err) }, "youtube-state.json unreadable; starting fresh");
    return {};
  }
}

function saveState(state: YouTubeStateFile): void {
  const path = stateFilePath("youtube");
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, JSON.stringify(state, null, 2) + "\n", "utf-8");
}

const KNOWN_RING_SIZE = 200;

function pushKnown(state: YouTubeChannelState, videoId: string): void {
  const known = state.knownVideoIds ?? [];
  if (known.includes(videoId)) return;
  known.push(videoId);
  if (known.length > KNOWN_RING_SIZE) known.splice(0, known.length - KNOWN_RING_SIZE);
  state.knownVideoIds = known;
}

// ─── 5. Write Markdown ────────────────────────────────────────────────

function writeMarkdownForVideo(
  video: VideoMeta,
  channelHandle: string | undefined,
  body: string,
  status: "ok" | "unavailable" | "partial",
  meta: { language?: string; languageName?: string; segmentCount?: number; isAutoGenerated?: boolean }
): string {
  const channelSlug = channelHandle?.replace(/^@/, "") ?? slugify(video.channelName);
  const dir = rawDir("youtube", channelSlug);
  mkdirSync(dir, { recursive: true });
  const path = resolve(dir, `${isoDate(video.publishedAt)}-${slugify(video.title)}.md`);
  const md = renderMarkdown({
    source: "youtube",
    source_id: video.channelId,
    content_id: video.videoId,
    url: video.url,
    author: video.channelName,
    published_at: video.publishedAt,
    title: video.title,
    body: status === "ok" ? body : "*(transcript unavailable for this video)*",
    transcript_status: status,
    ...(meta.language && { language: meta.language }),
    ...(meta.languageName && { language_name: meta.languageName }),
    ...(typeof meta.segmentCount === "number" && { segment_count: meta.segmentCount }),
    extras: {
      channel_handle: channelHandle ?? "",
      ...(meta.isAutoGenerated !== undefined && { auto_generated: meta.isAutoGenerated }),
    },
  });
  writeFileSync(path, md, "utf-8");
  return path;
}

// ─── Main: ingest one channel end-to-end ──────────────────────────────

export interface IngestChannelOptions {
  channelId: string;
  channelName: string;
  channelHandle?: string;
  /** Soft cap on new videos per run (defaults to 50; protects against insane backfills). */
  maxNewPerRun?: number;
}

export async function ingestYouTubeChannel(opts: IngestChannelOptions): Promise<IngestSummary> {
  const t0 = Date.now();
  const { channelId, channelName, channelHandle, maxNewPerRun = 50 } = opts;
  const errors: string[] = [];

  log.info({ channelId, channelName }, "starting channel ingest");

  // 1. Discover via RSS.
  let videos: VideoMeta[];
  try {
    videos = await discoverRecentVideos(channelId, channelName);
  } catch (err) {
    const error = err instanceof Error ? err.message : String(err);
    log.error({ channelId, error }, "RSS discovery failed");
    return {
      channelId,
      channelName,
      discovered: 0,
      alreadyKnown: 0,
      newWithTranscript: 0,
      newWithoutTranscript: 0,
      errors: [`rss: ${error}`],
      durationMs: Date.now() - t0,
    };
  }

  // 2. Filter against state.
  const state = loadState();
  const channelState: YouTubeChannelState = state[channelId] ?? {};
  const known = new Set(channelState.knownVideoIds ?? []);
  const fresh = videos.filter((v) => !known.has(v.videoId)).slice(0, maxNewPerRun);

  log.info(
    { channelId, discovered: videos.length, alreadyKnown: videos.length - fresh.length, fresh: fresh.length },
    "discovery complete"
  );

  if (fresh.length === 0) {
    channelState.lastChecked = new Date().toISOString();
    state[channelId] = channelState;
    saveState(state);
    return {
      channelId,
      channelName,
      discovered: videos.length,
      alreadyKnown: videos.length,
      newWithTranscript: 0,
      newWithoutTranscript: 0,
      errors: [],
      durationMs: Date.now() - t0,
    };
  }

  // 3. Batch fetch transcripts.
  const transcripts = await fetchTranscriptsBatch(fresh.map((v) => v.videoId));

  // 4 + 5. Write Markdown for each.
  let withTranscript = 0;
  let withoutTranscript = 0;
  for (let i = 0; i < fresh.length; i++) {
    const video = fresh[i]!;
    const t = transcripts[i]!;
    try {
      if (t.status === "ok") {
        writeMarkdownForVideo(video, channelHandle, t.text, "ok", {
          ...(t.language && { language: t.language }),
          ...(t.languageName && { languageName: t.languageName }),
          segmentCount: t.segments.length,
          ...(t.isAutoGenerated !== undefined && { isAutoGenerated: t.isAutoGenerated }),
        });
        withTranscript++;
      } else {
        writeMarkdownForVideo(video, channelHandle, "", "unavailable", {});
        withoutTranscript++;
        if ("error" in t && t.error) errors.push(`${video.videoId}: ${t.error}`);
      }
      pushKnown(channelState, video.videoId);
    } catch (err) {
      errors.push(`${video.videoId}: ${err instanceof Error ? err.message : String(err)}`);
    }
  }

  // 6. Persist state.
  channelState.lastChecked = new Date().toISOString();
  channelState.lastVideoId = fresh[0]?.videoId ?? channelState.lastVideoId;
  channelState.lastError = errors.length > 0 ? errors[0]! : null;
  state[channelId] = channelState;
  saveState(state);

  const summary: IngestSummary = {
    channelId,
    channelName,
    discovered: videos.length,
    alreadyKnown: videos.length - fresh.length,
    newWithTranscript: withTranscript,
    newWithoutTranscript: withoutTranscript,
    errors,
    durationMs: Date.now() - t0,
  };
  log.info(summary, "✓ channel ingest complete");
  return summary;
}
